// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// 

//  import 'firebase_options.dart';

//  await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkDWs5n-jTLilzQW6qxS--D9Tkoqiu5O4',
    appId: '1:581180243690:web:dee302412d44dd9e682193',
    messagingSenderId: '581180243690',
    projectId: 'dawak-app',
    authDomain: 'dawak-app.firebaseapp.com',
    storageBucket: 'dawak-app.appspot.com',
    measurementId: 'G-Y69SZDK95Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIuxzsnUMdvd2Vn4VKFAD0bUiDwNjd-iU',
    appId: '1:581180243690:android:6281040cd7b18dbb682193',
    messagingSenderId: '581180243690',
    projectId: 'dawak-app',
    storageBucket: 'dawak-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDUUbdg9cVByPly_v7NH-y4hGUcIPcgzk',
    appId: '1:581180243690:ios:f58b7ff7bc5c3134682193',
    messagingSenderId: '581180243690',
    projectId: 'dawak-app',
    storageBucket: 'dawak-app.appspot.com',
    iosBundleId: 'com.example.dawak24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDUUbdg9cVByPly_v7NH-y4hGUcIPcgzk',
    appId: '1:581180243690:ios:f58b7ff7bc5c3134682193',
    messagingSenderId: '581180243690',
    projectId: 'dawak-app',
    storageBucket: 'dawak-app.appspot.com',
    iosBundleId: 'com.example.dawak24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkDWs5n-jTLilzQW6qxS--D9Tkoqiu5O4',
    appId: '1:581180243690:web:85261819fea20ec5682193',
    messagingSenderId: '581180243690',
    projectId: 'dawak-app',
    authDomain: 'dawak-app.firebaseapp.com',
    storageBucket: 'dawak-app.appspot.com',
    measurementId: 'G-DTJDFJNCXD',
  );
}
